create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  description text not null check (char_length(description) between 1 and 240),
  contact text,
  image_key text not null unique,
  image_type text not null,
  claimed boolean not null default false,
  seller_sub text,
  claimed_by_sub text,
  created_at timestamptz not null default now(),
  constraint listings_contact_length
    check (contact is null or char_length(contact) between 1 and 200)
);

alter table public.listings enable row level security;
revoke all on table public.listings from anon, authenticated;
grant all on table public.listings to service_role;
grant usage, select on sequence public.listings_id_seq to service_role;

create index if not exists listings_created_at_idx
  on public.listings (created_at desc, id desc);
